version: '3.8'

networks:
  app-network:

volumes:
  app-data:

services:
  nginx:
    image: nginx:1.21.6-alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - .docker/nginx:/etc/nginx/conf.d
    networks:
      app-network:
  php:
    build:
      context: .docker/php
      dockerfile: dockerfile
    container_name: php
    env_file: .env
    volumes:
      - ./backend:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - app-data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network